name: gateway-deploy

on:
  repository_dispatch:
    types: [gateway-deploy-trigger] # This allows the workflow to be triggered by the parent workflow

jobs:

  deploy:
    runs-on: ['self-hosted', 'linux', 'x64', 'recipe-api']
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Pull Docker image
        run: docker pull okarkach1989/gateway:latest
      - name: Stop and remove previous container
        run: |
          if [ "$(docker ps -q -f name=gateway)" ]; then
            docker stop gateway
          fi
          if [ "$(docker ps -a -q -f name=gateway)" ]; then
            docker rm gateway
          fi
      - name: Run the latest Docker image
        run: docker run -d -p 9000:8080 --name gateway okarkach1989/gateway:latest
