name: menu-api-build

on:
  push:
    branches:
      - master 
    paths:
      - 'src/Menu/**'

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ~/.docker/cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file:  src/Menu/Menu.API/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/menu-api:latest
        platforms: linux/amd64
        build-args: |
          DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}
          RABBIT_HOST=${{ secrets.RABBIT_HOST }}
          RABBIT_PASSWORD=${{ secrets.RABBIT_PASSWORD }}
          RABBIT_USERNAME=${{ secrets.RABBIT_USERNAME }}
          VERSION=${{ github.sha }}

    - name: Trigger Deploy Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        event-type: deploy-menu-api

        